### ISSUE TITLE
links from "recent examples" don't handle special chars

### ISSUE THREAD

**Issue by cellularmitosis** [swlkr/janetdocs#18]
Adding some examples to Janetdocs today, I really enjoy it!  🤩

Found an issue:

If you search for `pos?`, the link takes you to https://janetdocs.com/pos_q, which is correct.

However, if you browse through "Recent examples" to the example I added for `pos?`, the `pos?` link points to `https://janetdocs.com/pos?`, which is a 404 (because https://janetdocs.com/pos is a 404).

**Comment by cellularmitosis** [comment]
found another one: `https://janetdocs.com/%3d` vs `https://janetdocs.com/=`

**Comment by swlkr** [comment]
Haha I originally started down the path of replacing `?` with `_q` for better urls, but I gave up and just encoded it from recent examples, so now you can get to `https://janetdocs.com/pos_q` and `https://janetdocs.com/pos%3f` 😅

Closed by 5f36a19
