### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by uvtc** [swlkr/janetdocs#22]
I'm finding that for me (on Debian Testing), the search functionality of the site is not working. Regardless of what I type into the search bar, nothing comes up. I can still manully type in the full url and get the docs and examples though. I tried this on both Firefox and Chromium.

**Comment by swlkr** [comment]
I accidentally overwrote the body from the form body parser middleware 🤦‍♂️

Closed by https://github.com/joy-framework/joy/commit/2659afeb4f856cfd949c268b4935584f23e45748

**Comment by sogaiu** [comment]
Thanks for the explanation :)
