### ISSUE TITLE
Add option to add "see also" links to other functions

### ISSUE THREAD

**Issue by felixr** [swlkr/janetdocs#24]
I think it would be useful be able to link to other functions that are related to the one you are currently looking at.

There are at least two good reasons for linking to other functions/etc:

**1. Functions/macros that interact with each other**

`return` (https://janetdocs.com/return) will always be used together with `prompt` (https://janetdocs.com/prompt). Users likely want to look at both docs in order to understand how they interact.

**2. Improve discoverability of related functions**

`file/read` (https://janetdocs.com/file%2fread) should link to `slurp` (https://janetdocs.com/slurp) to avoid users copying the `read-from-file` example instead of using `slurp`

**Comment by sogaiu** [comment]
I'm just a fellow appreciator of this project, but I like this idea.

I wonder how it might be achieved?

**Comment by pepe** [comment]
I also think this is a good idea.

**Comment by swlkr** [comment]
Oh yeah! That is a great idea! It might be possible to do it manually?

**Comment by felixr** [comment]
It probably makes sense to just keep a static list in the repository and use PRs to add new "see also" links. Making a UI to edit them is unnecessary work and it would also raise the question who can edit a link.

I hacked around a bit and added another table for links and a tiny bit of code to list them. It looks like this: 
![see also links](https://user-images.githubusercontent.com/1200407/101663028-15a01f80-3a42-11eb-8fbb-072de9064835.gif)

**Comment by swlkr** [comment]
Whoa! Nice! Yeah that's a good idea, the best UI is the one you already have (PRs)

Wait is this real code? PR incoming?

**Comment by felixr** [comment]
Yes, real code. Will send a PR once I did some clean up.

**Comment by swlkr** [comment]
Closed by #27
