### ISSUE TITLE
Please specify license

### ISSUE THREAD

**Issue by felixr** [swlkr/janetdocs#25]
I thought about contributing a PR for janetdocs#24, but then noticed that the project has no license.
It would probably good in general to specify the license, but I, for example, cannot contribute unless the project is under one of my employer's approved open-source licenses.

**Comment by swlkr** [comment]
Ahh, how does MIT sound?

**Comment by felixr** [comment]
Sounds good. But any of the popular open-source licenses would work for me. So up to you :-)

**Comment by swlkr** [comment]
Done and done

**Comment by felixr** [comment]
Thank you, and also thanks for creating janetdocs.com. I am doing Advent of Code to learn Janet and found it very helpful as I still have to look up stuff quite often.
