### ISSUE TITLE
Incorrect syntax highlighting in editor preview

### ISSUE THREAD

**Issue by Krasjet** [swlkr/janetdocs#29]
For the following example in [interleave](https://janetdocs.com/interleave):
```
# excess elements of the longer list are discarded
(interleave [1] 
            [2 4] 
            [3 6])
# -> @[1 2 3]
```
The `#` on the first line comments out the entire code snippet in preview mode,
![pick-201213-223409](https://user-images.githubusercontent.com/5229241/102037508-4ad6a580-3d93-11eb-9854-3f4468d01db1.png)
but the syntax highlighting behaves correctly after I submitted the example.
![pick-201213-223448](https://user-images.githubusercontent.com/5229241/102037565-693ca100-3d93-11eb-81eb-90f6f9260cfa.png)

I suspect it has something to do with how code are stored in `textarea`, but I am not familiar with highlight.js so unfortunately I can't locate the problem in the code.

**Comment by Krasjet** [comment]
Oops, possible duplicates with #14.

**Comment by Krasjet** [comment]
I think I have located the problem. This is related to https://github.com/alpinejs/alpine/commit/f70a71ef4275ead4baa38cfef1bcd4c4c67659fa.

Setting `element.innerText` converts line-breaks (`\n`) to `<br>` tag automatically. The correct way to change the content of an element is to set `element.textContent`. Since janetdocs uses `x-text` from alpine.js internally, you need to update alpine.js to at least v2.7.0 to fix this issue.

**Comment by swlkr** [comment]
Yes!!

Two issues for the price of one!

Two birds in the bush is one in the hand?

**Comment by swlkr** [comment]
Thanks for doing the heavy lifting on that one!
