### ISSUE TITLE
Help with test environment (for janet-playground pull request)

### ISSUE THREAD

**Issue by MikeBeller** [swlkr/janetdocs#33]
Hi @swlkr  -- based on the conversation over at https://github.com/janet-lang/janet/discussions/570 in which you participated, I'm working on a PR to demonstrate integration of janet-playground into janetdocs.

I forked janetdocs and sort of got it running locally.  But I had to guess at a bunch of things.  (Like how to initialize the db, etc.)

Is there a test db?  Is there an environment file I should use for testing?  Can you disable the oauth for testing?  

Any guidance would be appreciated.

-Mike

**Comment by swlkr** [comment]
Hey I added a readme and an `.env.sample` file to show all of the required env variables.

The readme should get you up and running, let me know if anything is unclear still

**Comment by MikeBeller** [comment]
Thanks @swlkr will do.

**Comment by MikeBeller** [comment]
When you create the API key, what powers do you need to give it on Github?

**Comment by swlkr** [comment]
Oh it's an oauth key, not an application key or something

I should point that out in the readme

https://docs.github.com/en/developers/apps/authorizing-oauth-apps

**Comment by MikeBeller** [comment]
If I want to create these github ID's I think I need to fill out this form:  https://github.com/settings/applications/new

 -- it's making me give a URL for the app (https://janetdocs.com presumably) and a callback URL (which from the routes in main.janet is probably https://janetdocs.com/github-auth )  Is it weird that I would be essentially re-registering your app and your domain in order to get these keys?  I am only planning on testing this on localhost.

**Comment by swlkr** [comment]
Oh I just set the callback url to `http://localhost:9001/github-auth`

I also have two set up, one for prod and one for dev, wasn't sure how else to do it

**Comment by swlkr** [comment]
I don't think you need ngrok or anything, but I could be wrong (about forwarding to localhost)

**Comment by MikeBeller** [comment]
Perfect.  It's working now.  Thanks.
