### ISSUE TITLE
a way to fix / edit a broken example?

### ISSUE THREAD

**Issue by uvtc** [swlkr/janetdocs#44]
Is there a way to fix or edit a broken example?

As pointed out at https://github.com/janet-lang/janet/issues/983 the "add17" example for [partial](https://janetdocs.com/partial) is broken (should be `def` instead of `defn`).

**Comment by sogaiu** [comment]
For this specifc case, pinging @cellularmitosis might lead to an eventual fix.  It seems inevitable though that some folks will not be reachable at some point.

Perhaps filing issues in this repository could be part of a more general approach?

**Comment by swlkr** [comment]
It could be cool to have an edit history with who edited what and when

**Comment by cellularmitosis** [comment]
fixed, thanks!

**Comment by uvtc** [comment]
Ooof! I didn't even check to see if I could edit the examples I've added! I see that the original author can indeed edit their examples, and that @cellularmitosis went and fixed the item under discussion. Closing this issue. Thanks, all.

**Comment by sogaiu** [comment]
@uvtc It's nice that in this case it worked out, but it seems inevitable that there will be folks that are not reachable (soon or ever) at some point.
