### ISSUE TITLE
tabseq doesn't show up

### ISSUE THREAD

**Issue by sogaiu** [swlkr/janetdocs#47]
Is there support for [`tabseq`](https://janet-lang.org/api/index.html#tabseq)?

I'm not seeing a page for it.

**Comment by swlkr** [comment]
Oh no, my "manual until I absolutely have to automate it" strategy is catching up with me. Let me put it in there

**Comment by sogaiu** [comment]
Thanks for taking a look!

**Comment by swlkr** [comment]
finally managed to ssh in and add it https://janetdocs.com/tabseq

**Comment by sogaiu** [comment]
@swlkr Thanks a bunch!
